apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.lower }}-{{ .Values.name }}-svc
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.lower }}-{{ .Values.name }}